#!/bin/sh

mkdir -p /home/git && \
cd /home/git && \
git clone --branch learning --depth=1 https://github.com/mshgh/netcore-test-docker.git repo && \
cd repo

echo
echo "Checking repository for docker build parameter files..."
for PARAMS_FILE in $(find . -name docker-build.env); do
  echo
  echo "Found: $PARAMS_FILE"

  . $PARAMS_FILE

  docker build \
    --target builder \
    --cache-from $_B_DOCKER_IMAGE:builder \
    --tag $_B_DOCKER_IMAGE:builder \
    --file src/Dockerfile.common
    .

  docker build \
    --cache-from $_B_DOCKER_IMAGE:builder \
    --cache-from $_B_DOCKER_IMAGE:latest \
    --tag $_B_DOCKER_IMAGE:$_B_APP_VERSION \
    --tag $_B_DOCKER_IMAGE:latest \
    --file src/Dockerfile.common
    .

  //docker build $(cat $PARAMS_FILE | sed '/^#/ d' | sed 's/$/ /' | tr -d '\n')
done
